server:
  port: 8089

spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
  datasource:
    url: jdbc:mysql://localhost:3306/buy_ticket?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 060615
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload:
    path: uploads

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.buyticket.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

alipay:
  app-id: 2021006120699092
  merchant-private-key: "MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQCo4Nm2s5DrnO70IyKKKJxlgdf5yp4TWxL3Pn9Ghv8vXF7flcO/lK+L83lD8spw2Tn2Tu+cQnWSdgV29NUoNeuhvUvfDYR6P0h/DIkBaCXBoEKo3hYA8PycoigVoBTvo/fv+PXOnyPJi1xGthtS1yGUlnrbP0rAMjVGcs4hSg+zMUnd/qKHQG8ZQCSvM9fl1apSgUgqphSSkNF4VILNtzOydfqZNIX+shSdRcS+xX5xnhIv3+m8lyZ7c7N+Rr1WXo3M2Thuxe3YhhSqJWp9gnFjyaWEOfZ3LJByp/ul4oOswy7AQjRXyu489hEl0x5peVLiqNpsQivzW536qtiuRJwPAgMBAAECggEBAI0HIKjTMb2g02frg2eO3HRkR0EhdHrDfoYcmdsC103svInInqx5dVPRIj6dHXO55A6OAskiMt75Ujzx3qPyy3DJDPgbaLtR56+5fxw+pfEZbTFqLUPh+4KuY/0TLwikjGPJKzS+bvtbNtcSMqUuZKuaMsSvCTSReS34p6zjFVNVBIDQYmFZaPY4A5V/2WuhUPfXizggCoBAC2UY+D6aI6/Gu5LgRI2a+cNJ05UaHl+a3LEqGGsYXoRY0yXO7ZYpZsp5nJqfNxGnTQ4bMfX1MZB0cn/1GFQiiefRQdRsHy03Vs0ANEJKnSVb7hek8yw0IBMJqnFW9AESSlxF/P2gb+ECgYEA4Lez+2wjG3AG2u2UlsavIoz0fSjZdn1MKyuLvQozzjQjZ/rFAE3X1rcBGR+olswapLm1nLN1/jQhJBYBEIes3jni/gTBAjUueRNJ04Z4V2pXQKFgyTqQtpsL1xGL8YHCwHLBSnQ8gqOuoVLOIeQiSfM5ClC6kvdT/VJ2Age1Dp8CgYEAwGMxxF2R8nUr8G48vqDtSH4RvA3nV6RPo5FLltN54YGV5n6g9SwpJqyLQrQVfktdnzP22W7Hf8FvJIREZ9JjslDSzez1vjzqTGezqCK/BNtRg/eC3Bftf4aNGMK7E1tZ/1IRoemWGoIT7M/DgD7vpkGLNRP6arfinwDTkkVMLJECgYEAtEvwBhu/FzaM6X6RJ2AGCGybhQgPYngpcsGffm7/HcTLW5PiF9pdAJMYOHYkJ8le3yd5RV7fnrNom7Fj7UVON4auTyy1RvYwcUg+hY5wY4KYuuw/4XQxw7EmkMotQ/nerdXkq74TBqYZaKotZRfLQxX4gARBjcUPCELvF7XjWPUCgYEAnT+2ytjsVO/+xRtlnS6uI+Wfm0UGBXWw/nHhBdu+sFqZ6ncwGpVI4WqAvTmyo7L4SAtSRfCtMbgqnv9ZZj7p7DLxyw1W43Ko02Cj0NbtqQuWejYRiNIp9mVE6Ksp+61cRzuOW/gwD2So4pQDKMzIVu0V2oGE2juJCQvE4ravh3ECgYEAyjSotxY3oK6n085IhnooIr4iTY59n8pQkw1oef44AWX5Whbq1+4SotARqSBN1hWQ26nRrdGTurGKHSUKh21hHeRGCR1hFWdQ+yFXQdUqZxT8BWMU5jDo4FF3OA0fEt8BvvtEiE1Z2PK0GG+sX3FL0BImXOjUZcrR6nfiNbO5Fqg="
  alipay-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3buUX4ZG1cWCNT/SddGj+RVcmm/PWUGX2wkzhL5qt346vjArTLXuEAVXcGiywDFPfaroq9RGUtO95fIesiKo2K1g90U6Mhzk1h/s3tO41A3EZww0dBwMVJebmAqy/xZc7LD4rhhlLJBiyMSebsFLG0+e17JnscalaeW7wy8VUKCPx6rbQnVvFULd9MgTu5vVawgOmRt6DYX8vFM5DyBYLcBH5Bjjfg35nMnPiVHXGqgSfwZsEiGz+TAtQHTsHakJtX5h3G/kvA6lVXrlJl75nsQIwYlG2ff50u9pssTKwBBIJqBdgtB0uFf5jQqBoJb8kyvFXcdKv+Z3xwgOOJ/3rQIDAQAB"
  notify-url: https://ai-yishuguan.com/api/v1/payment/alipay/notify
  return-url: https://ai-yishuguan.com/order-success
  gateway-url: https://openapi.alipay.com/gateway.do
  sign-type: RSA2
  charset: utf-8

aliyun:
  sms:
    enabled: true
    accessKeyId: YOUR_ACCESS_KEY_ID
    accessKeySecret: YOUR_ACCESS_KEY_SECRET
    signName: 元星河文化
    templateCode: SMS_501865326

# 汇付宝支付配置
huifu:
  merchant-id: "6666000183050701"
  product-id: "PAYUN"
  huifu-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm8VQwWkmUtQvi6byTq92/Iq5abGo+ZAEkr7/gBcJPW+6JZWqYpH7zldJz5PL6/YuDSp/hYQtGEU60L/iXzvF1xr1fZ/NHS9Hk6XQITV35TmwVXNKETChuzhVp/YMnoJJOzTu2Jf5gsJvzRYzF8lcGa9mxIGgWsiC/CkXnCGPQAtCCZ+zUl5ixT2Okt094FBITDr7yAU7mjhTIX4LEieGaq092chFtBpCfELRYscWWgl1l2L1BXBfmwQdx+zqnr8JH3Cs/q5NWkjXQWLC6Me00weJZs61JLTVv+BjYp+cCBFga9236BBaBJuy/9J4tmyt/8XPfNCDsCSTcJpoEMS/UwIDAQAB"
  merchant-private-key: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCJbSWn6TpGFS7pIpNCzg0ad7ZikGBgkIaozBPbvMcC0vxBj5XuRgy05JKtZAUfowm5cR8D7jqyRsH6W47lT1oTuy+EuMwUneJJKdGEreLIaDdpg/bwmd8oOZt8IcRkwmH0JMDqqigAW8hj7CnuzFo4a3vW1szXFrX4cbMV/aTLMjmuauMcXBFG/lt9UB9ytguAjJksVPyFlnoDqi2OzpS5Vr1ywF1hBdxhELzeZBZCOcG5T9B6S0Ikqg2BOGWOw6/pVwivB3S7rWVrUcb1syIZu1T5cHGHPoxeu7XGEMIs1pYsAZgRawdfcSu4JzBAJY6SanPzVInLsCD+ANs9We9DAgMBAAECggEAB5Wni2Ha3n1SznkjCX/Xx0suHLh9KTcwx2Yj/m+nyCce1vt2ueTR1LX8xmcLxVg5NCvjG1Ntl+NB13BwLYW4ofglwjx0vvqLv5/4OUtjhc4CqOconNTRNSYgx7QRY8I6p7/TieAEPyjRoXoqQkyy+gQsnInUWladim20BZWvH6u8OyQTRGI+kS5Ny3GQ2rRqtDIeof8qB8MP+n1TyNG2kHgQXYiEMIzZinGTuehBrhkkNRqD3ddgUGdeWkhdfikjSYpsDASTSY2ctQS6jD8fZMZPr4kuL4mfkqRnnzLmfzVuvcvhwHfUynmL6MwfiHATJwgoOsHmjZM903LHZn3TUQKBgQDEnRuaqz7YNxI9B5pLlOm1YojNb22ro0kYOJYHDZrEfHbrXASaKgxyJwuJ2kjgzY8wnJh7QFxCZrGTcnDZxwJnHo83H7esWtr/MKikVs1zphD3k68Nvkg3uYVEAXBZu2ourojPdmFTFKoq7GdD5VE2Ok1KkPhNB70xQSaBszpdCQKBgQCy73ToS1qXBhfufa66lHRC0pRDe/HcG3vCXVpXeNDE+Kvz8tuhu4leYtmo00V95/l2IPt+QG2JfU2RXjYLbLD5VRlh+/scqhVD25OUOCcIsxo7Ar9/nsrvxP46lxSA7JSJzPsdp5hNJgUwVWiPqwwlcrRAdqn/yvhtvhWHqrxI6wKBgQCy5gFoCsl0EygVQAW1IBpHYRD5XJp9wmWQFGzungJlJptOLLxDSl9ovv5QwL3vTxsrMFHOVBGembKaZ1cn0VzuV3AYyFNoEIOUD8JjRlhLEp/9pfNyneE4UyZfaq+/9jf3off6Tczgu7zasaCEtvPeU85gOuizrocHejB/c4V3gQKBgQCeJk6p0ZAr01Lrk2IPvo5TUVOBodbOt+vWijQDA+FhdnhkkM3WUK7FIZFHShQtiA5Qfi5KFB+8WWdpiF80EckJVlGs7M2xNBK/ex8g7dByO/p/FZqz7WFoMjCREF8q4+8VLHr2Zt6RsXz8j0BvWrrNjmgKYdc3IeoY9NyKoDjyKQKBgDv4kFUI6dtEwXsjU/4kK4CkNC8YXM39t6rtobCvx65EdzOCh5gRDep6CLOAGf56R44cn+7ChLjLPEJAiaYp8ZR6UGqhxFrbMYjeVV89F9Lz/oKZ0nAhN5LublEoF/dJHMbet0zLxohBNL03FsHtK/a6RBltlhoD92u190JNiYYh"
  notify-url: "https://ai-yishuguan.com/api/v1/huifu-pay/notify"
  return-url: "https://ai-yishuguan.com/order-success"
  gateway-url: "https://paas.huifu.com"

logging:
  level:
    root: INFO
    com.buyticket: INFO
  file:
    name: /var/log/buyticket/application.log
    max-size: 100MB
    max-history: 30
